INSERT INTO PRODUCTOS VALUES (null, 'Producto 101', 1);
INSERT INTO PRODUCTOS VALUES (null, 'Producto 102', 2);
INSERT INTO PRODUCTOS VALUES (null, 'Producto 103', 3);
INSERT INTO PRODUCTOS VALUES (null, 'Producto 104', 4);