INSERT INTO PRODUCTOS VALUES (null, 'Producto 41');
INSERT INTO PRODUCTOS VALUES (null, 'Producto 42');
INSERT INTO PRODUCTOS VALUES (null, 'Producto 43');
INSERT INTO PRODUCTOS VALUES (null, 'Producto 44');